<a href="https://colab.research.google.com/github/Jagadeeshkavuri1/ML_assignments/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [10]:
a1=np.arange(0,10,2)
print(a1)

[0 2 4 6 8]


In [17]:
a2 = np.linspace(0, 1, 4)
print(a2)  # Output: [0.   0.25 0.5  0.75 1.  ]


[0.         0.33333333 0.66666667 1.        ]


In [20]:
a = np.array([1, 2, 3, 4, 5,6])
b = a.reshape((2, 3))
print(b)
# Output:
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]


In [25]:
print(b.flatten())  # Output: [1 2 3 4]
print(b)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [26]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[0, 1])  # Access element at row 0, column 1 → 2
print(a[1])     # Access entire second row → [4 5 6]
print(a[:, 0])  # Access first column → [1 4]


2
[4 5 6]
[1 4]


In [27]:
d = np.array([1, 6, 3, 8, 5])
print(d[d > 5])  # Output: [6 8] boolean indexing


[6 8]


In [28]:
e = np.array([10, 20, 30, 40, 50])
indices = [1, 3, 4]
print(e[indices])  # Output: [20 40 50] fancy indexing


[20 40 50]


In [31]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # [5 7 9]  array operations
print(a * b)  # [4 10 18]
print(a ** 2) # [1 4 9]
print(np.dot(a, b))


[5 7 9]
[ 4 10 18]
[1 4 9]
32


In [32]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))  # Matrix multiplication


[[19 22]
 [43 50]]


In [35]:
a = np.array([1, 2, 3])
b = 2
print(a + b)  # [3 4 5] — b is "broadcasted" to [2 2 2]


[3 4 5]


In [36]:
a = np.array([1, 2, 3])
b = 2
print(a + b)  # [3 4 5] — b is "broadcasted" to [2 2 2]


[3 4 5]


In [37]:
a = np.array([1, 2, 3, 4])
print(np.sum(a))     # 10
print(np.mean(a))    # 2.5
print(np.max(a))     # 4
print(np.std(a))     # 1.118... aggregative function


10
2.5
4
1.118033988749895


In [40]:
print(np.random.randint(1, 10, (2, 3)))#random values of 1 to 10 and have 2 rows and 3 columns


[[9 4 4]
 [4 9 4]]


In [49]:
import numpy as np

a = np.array([1, 2, 3])
result = []
for i in a:
    result = [int(i) for i in a * 2]
print(result)


[2, 4, 6]


In [50]:
x = np.array([1, 2, 3])
y = x.view()
y[0] = 100
print(x)  # x is also affected → [100 2 3]

z = x.copy()
z[1] = 200
print(x)  # x is not affected → [100 2 3]


[100   2   3]
[100   2   3]
